from rest_framework import routers
from forms.viewsets import FormViewSet

router = routers.SimpleRouter()
router.register(r'forms',FormViewSet,basename='forms')
urlpatterns = router.urls

# The routers.SimpleRouter() is used to create a simple default router that automatically generates URLs for a DRF ViewSet.
# FormViewSet from forms.viewsets is registered with the router.
# The basename parameter in router.register is set to "forms". This basename is used to construct the URL names for the FormViewSet.
# Finally, urlpatterns = router.urls sets the urlpatterns for this part of the application to those generated by the router for the FormViewSet.
