# Generated by Django 5.2.3 on 2025-06-10 23:59

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('CaseID', models.AutoField(primary_key=True, serialize=False)),
                ('PatientID', models.CharField(editable=False, max_length=20, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Diagnosis', models.CharField(blank=True, max_length=255)),
                ('Confidence', models.CharField(blank=True, max_length=10)),
                ('Image', models.ImageField(upload_to=forms.models.get_upload_path)),
            ],
        ),
    ]
