# Generated by Django 5.2.3 on 2025-06-17 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_id", models.CharField(max_length=50, unique=True)),
                ("patient_id", models.CharField(max_length=50)),
                ("image_name", models.CharField(max_length=255)),
                ("image_path", models.CharField(blank=True, max_length=500, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="uploaded", max_length=20)),
            ],
            options={
                "db_table": "case_images",
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annotation_id", models.CharField(max_length=100, unique=True)),
                ("annotations_data", models.JSONField()),
                ("total_annotations", models.IntegerField(default=0)),
                ("positive_count", models.IntegerField(default=0)),
                ("negative_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="forms.caseimage",
                    ),
                ),
            ],
            options={
                "db_table": "annotations",
            },
        ),
        migrations.CreateModel(
            name="BoundingBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_id", models.IntegerField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("relative_x", models.FloatField()),
                ("relative_y", models.FloatField()),
                ("relative_width", models.FloatField()),
                ("relative_height", models.FloatField()),
                (
                    "label",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounding_boxes",
                        to="forms.annotation",
                    ),
                ),
            ],
            options={
                "db_table": "bounding_boxes",
                "unique_together": {("annotation", "box_id")},
            },
        ),
    ]
